"""Add problem model.

Revision ID: 0e4c23f246f3
Revises: 68e8dc54baaf
Create Date: 2015-12-20 00:53:26.469794

"""

# revision identifiers, used by Alembic.
revision = '0e4c23f246f3'
down_revision = '68e8dc54baaf'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('problem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('problem_desc', sa.Text(), nullable=True),
    sa.Column('input_desc', sa.Text(), nullable=True),
    sa.Column('output_desc', sa.Text(), nullable=True),
    sa.Column('sample_input', sa.Text(), nullable=True),
    sa.Column('sample_output', sa.Text(), nullable=True),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('visible', sa.Boolean(), nullable=False),
    sa.Column('test_case_count', sa.Integer(), nullable=False),
    sa.Column('time_limit', sa.Integer(), nullable=False),
    sa.Column('memory_limit', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('problem')
    ### end Alembic commands ###
