"""empty message

Revision ID: 3c941a7cbd74
Revises: dfcab1e08dd4
Create Date: 2015-12-24 18:33:22.418368

"""

# revision identifiers, used by Alembic.
revision = '3c941a7cbd74'
down_revision = 'dfcab1e08dd4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('submission', 'filename',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('submission', 'filename',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    ### end Alembic commands ###
