"""Add missing attributes for Submission.

Revision ID: 830ecec6f85f
Revises: e98d566b21f2
Create Date: 2015-12-21 18:17:27.599425

"""

# revision identifiers, used by Alembic.
revision = '830ecec6f85f'
down_revision = 'e98d566b21f2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submission', sa.Column('code_length', sa.Integer(), nullable=True))
    op.add_column('submission', sa.Column('memory_usage', sa.Integer(), nullable=True))
    op.add_column('submission', sa.Column('time_usage', sa.Integer(), nullable=True))
    op.add_column('submission', sa.Column('verdict', sa.Enum('Accepted', 'Wrong Answer', 'Runtime Error', 'Time Limit Exceeded', 'Memory Limit Exceeded', 'Restrict Function', 'Output Limit Exceeded', 'Presentation Error'), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submission', 'verdict')
    op.drop_column('submission', 'time_usage')
    op.drop_column('submission', 'memory_usage')
    op.drop_column('submission', 'code_length')
    ### end Alembic commands ###
