"""empty message

Revision ID: c13b2ca00422
Revises: 2dd4f4c4af8e
Create Date: 2015-12-30 23:21:21.451511

"""

# revision identifiers, used by Alembic.
revision = 'c13b2ca00422'
down_revision = '2dd4f4c4af8e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submission', sa.Column('contest_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'submission', 'contest', ['contest_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'submission', type_='foreignkey')
    op.drop_column('submission', 'contest_id')
    ### end Alembic commands ###
