"""empty message

Revision ID: c3a80b41fdb4
Revises: e802fcf7cd2e
Create Date: 2016-01-01 20:37:53.602640

"""

# revision identifiers, used by Alembic.
revision = 'c3a80b41fdb4'
down_revision = 'e802fcf7cd2e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('problem', sa.Column('public_time', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('problem', 'public_time')
    ### end Alembic commands ###
