"""Add Tutorial Model.

Revision ID: dfcab1e08dd4
Revises: ff57d8a1b7b9
Create Date: 2015-12-23 16:47:18.897387

"""

# revision identifiers, used by Alembic.
revision = 'dfcab1e08dd4'
down_revision = 'ff57d8a1b7b9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tutorial',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['post.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tutorial')
    ### end Alembic commands ###
