"""empty message

Revision ID: e802fcf7cd2e
Revises: 3ca04b2d3626
Create Date: 2016-01-01 10:15:24.329480

"""

# revision identifiers, used by Alembic.
revision = 'e802fcf7cd2e'
down_revision = '3ca04b2d3626'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('standing', sa.Column('actime', sa.Integer(), nullable=True))
    op.drop_column('standing', 'accepted')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('standing', sa.Column('accepted', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('standing', 'actime')
    ### end Alembic commands ###
